insert into roadmap_items (
    slug,
    title_de,
    summary_de,
    title_en,
    summary_en,
    dev_notes,
    status,
    visibility,
    horizon,
    priority,
    category,
    sort_order,
    completed_at,
    translation_status
) values
    (
        'fokus-timer',
        'Fokus-Timer',
        'Ein Timer, der Fokusphasen und Pausen gemeinsam plant.',
        'Focus timer',
        'A timer that plans focus sessions and breaks together.',
        'Die Dauerprofile sollen später serverseitig konfigurierbar werden.',
        'in_progress',
        'public',
        'short',
        'high',
        'Fokus',
        10,
        null,
        'reviewed'
    ),
    (
        'verschluesselter-anhang-sync',
        'Verschlüsselter Anhang-Sync',
        'Anhänge werden verschlüsselt zwischen Geräten synchronisiert.',
        'Encrypted attachment sync',
        'Attachments are synced between devices with encryption.',
        'Vor Umsetzung muss die Obergrenze pro Datei festgelegt werden.',
        'planned',
        'public',
        'mid',
        'normal',
        'Sync',
        20,
        null,
        'auto'
    ),
    (
        'homescreen-widgets',
        'Homescreen-Widgets',
        'Widgets zeigen die nächsten Aufgaben und den aktuellen Fokus an.',
        'Home screen widgets',
        'Widgets show upcoming tasks and the current focus.',
        null,
        'done',
        'public',
        'short',
        'normal',
        'Widgets',
        30,
        '2026-07-20',
        'reviewed'
    ),
    (
        'macos-app',
        'macOS-App',
        'Eine eigenständige Desktop-App ergänzt die iOS-App.',
        null,
        null,
        'Interne Machbarkeitsprüfung; noch nicht öffentlich ankündigen.',
        'planned',
        'internal',
        'long',
        'high',
        'Plattformen',
        40,
        null,
        'missing'
    ),
    (
        'team-bereiche',
        'Gemeinsame Team-Bereiche',
        'Aufgaben und Roadmaps können in einem Team geteilt werden.',
        null,
        null,
        'Konzept verworfen, solange Ende-zu-Ende-Verschlüsselung nicht geklärt ist.',
        'cancelled',
        'draft',
        'long',
        'low',
        'Zusammenarbeit',
        50,
        null,
        'missing'
    ),
    (
        'sprachmemos',
        'Sprachmemos',
        'Kurze Sprachaufnahmen lassen sich direkt als Aufgabe erfassen.',
        'Voice memos',
        'Short voice recordings can be captured directly as tasks.',
        null,
        'planned',
        'public',
        'mid',
        'low',
        'Erfassung',
        60,
        null,
        'auto'
    );

insert into changelog_entries (
    app_version,
    released_on,
    change_kind,
    title_de,
    body_de,
    title_en,
    body_en,
    visibility,
    roadmap_item_id,
    sort_order,
    translation_status
) values
    (
        '2.1.0',
        '2026-07-20',
        'added',
        'Neue Homescreen-Widgets',
        'Die neuen Widgets zeigen anstehende Aufgaben und den aktuellen Fokus.',
        'New home screen widgets',
        'The new widgets show upcoming tasks and the current focus.',
        'public',
        (select id from roadmap_items where slug = 'homescreen-widgets'),
        10,
        'reviewed'
    ),
    (
        '2.1.0',
        '2026-07-20',
        'changed',
        'Verbesserte Fokusansicht',
        'Die Fokusansicht reagiert schneller und zeigt Pausenzeiten deutlicher an.',
        'Improved focus view',
        'The focus view responds faster and displays break times more clearly.',
        'public',
        (select id from roadmap_items where slug = 'fokus-timer'),
        20,
        'reviewed'
    ),
    (
        '2.0.1',
        '2026-07-12',
        'fixed',
        'Sync-Konflikte behoben',
        'Ein interner Teststand behebt Konflikte beim parallelen Bearbeiten.',
        null,
        null,
        'internal',
        (select id from roadmap_items where slug = 'verschluesselter-anhang-sync'),
        30,
        'missing'
    ),
    (
        '2.0.0',
        '2026-07-01',
        'removed',
        'Alte Team-Experimente entfernt',
        'Nicht veröffentlichte Team-Experimente wurden aus dem Entwicklungsstand entfernt.',
        null,
        null,
        'draft',
        (select id from roadmap_items where slug = 'team-bereiche'),
        40,
        'missing'
    );
